=== Ramplorer/Grundlagen-von-Informationssystemen/data/formulareingaben.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD fÃ¼r Formulareingaben -->

<!ELEMENT formulareingaben (eingabe+)>
<!ATTLIST formulareingaben version CDATA #REQUIRED>

<!ELEMENT eingabe (nameM?, nameL?, ticker?, sektor?, investmentThese?, chance?, risiko?, upside?, buch1?, autor1?, warum1?, buch2?, autor2?, warum2?, buch3?, autor3?, warum3?, datum?)>

<!-- Eingaben Marco -->
<!ELEMENT nameM (#PCDATA)>
<!ELEMENT ticker (#PCDATA)>
<!ELEMENT sektor (#PCDATA)>
<!ELEMENT investmentThese (#PCDATA)>
<!ELEMENT chance (#PCDATA)>
<!ELEMENT risiko (#PCDATA)>
<!ELEMENT upside (#PCDATA)>

<!-- Eingaben Lara -->
<!ELEMENT nameL (#PCDATA)>
<!ELEMENT buch1 (#PCDATA)>
<!ELEMENT autor1 (#PCDATA)>
<!ELEMENT warum1 (#PCDATA)>
<!ELEMENT buch2 (#PCDATA)>
<!ELEMENT autor2 (#PCDATA)>
<!ELEMENT warum2 (#PCDATA)>
<!ELEMENT buch3 (#PCDATA)>
<!ELEMENT autor3 (#PCDATA)>
<!ELEMENT warum3 (#PCDATA)>

<!-- Gemeinsam -->
<!ELEMENT datum (#PCDATA)>

=== Ramplorer/Grundlagen-von-Informationssystemen/data/formulareingaben.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formulareingaben SYSTEM "formulareingaben.dtd">
<formulareingaben version="1.0">
  <eingabe>
    <nameL>Lara Muster</nameL>
    <buch1>The Secret History</buch1>
    <autor1>Donna Tartt</autor1>
    <warum1>Die Spannung und die komplexen Charaktere</warum1>
    <buch2>Die Verwandlung</buch2>
    <autor2>Franz Kafka</autor2>
    <warum2>Ein gesellschaftskritisches Meisterwerk</warum2>
    <buch3>Die Tribute von Panem</buch3>
    <autor3>Suzanne Collins</autor3>
    <warum3>Die starken Charaktere und die packende Handlung</warum3>
    <datum>2025-01-15 14:30:00</datum>
  </eingabe>
  <eingabe>
    <nameM>Marco Arnold</nameM>
    <ticker>NVDA</ticker>
    <sektor>Halbleiter</sektor>
    <investmentThese>KI-Revolution und starke Marktposition</investmentThese>
    <chance>KI-Boom, autonomes Fahren, Datenzentren</chance>
    <risiko>Regulierung, Konkurrenz</risiko>
    <upside>+50% in 12 Monaten</upside>
    <datum>2025-01-16 10:15:00</datum>
  </eingabe>
  <eingabe>
    <nameL>Anna Schmidt</nameL>
    <buch1>1984</buch1>
    <autor1>George Orwell</autor1>
    <warum1>Zeitlose Warnung vor Totalitarismus</warum1>
    <buch2>Der Herr der Ringe</buch2>
    <autor2>J.R.R. Tolkien</autor2>
    <warum2>Epische Fantasy-Welt</warum2>
    <buch3>Harry Potter</buch3>
    <autor3>J.K. Rowling</autor3>
    <warum3>Magische Welt voller Abenteuer</warum3>
    <datum>2025-01-17 16:45:00</datum>
  </eingabe>
  <eingabe>
    <nameM>Thomas M체ller</nameM>
    <ticker>TSLA</ticker>
    <sektor>Elektrofahrzeuge</sektor>
    <investmentThese>F체hrungsposition in E-Mobilit채t und erneuerbaren Energien</investmentThese>
    <chance>Energiewende, autonomes Fahren</chance>
    <risiko>Volatilit채t, Konkurrenz</risiko>
    <upside>+30% in 6 Monaten</upside>
    <datum>2025-01-18 09:20:00</datum>
  </eingabe>
</formulareingaben>

=== Ramplorer/Grundlagen-von-Informationssystemen/formulareingaben_lara.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formulareingaben SYSTEM "formulareingaben.dtd">
<formulareingaben version="1.0">

    <!-- Eingabe 3: Lara's Bücher Formular -->
  <laraEingaben id="lara-001">
    <name>Lara Muster</name>
    <buch1>The Secret History</buch1>
    <autor1>Donna Tartt</autor1>
    <warum1>Die Spannung, die das Buch mit sich bringt, ist atemberaubend. Die Charakterentwicklung ist meisterhaft und die Atmosphäre an der Universität fesselt einen von der ersten Seite an.</warum1>
    <buch2>Die Verwandlung</buch2>
    <autor2>Franz Kafka</autor2>
    <warum2>Da es ein gesellschaftskritisches Buch ist, das auf eine einzigartige Weise die Absurdität des modernen Lebens darstellt. Kafkas Schreibstil ist unvergleichlich.</warum2>
    <buch3>Die Tribute von Panem</buch3>
    <autor3>Suzanne Collins</autor3>
    <warum3>Die starken Charaktere, besonders Katniss, sind inspirierend. Die Dystopie ist packend erzählt und regt zum Nachdenken über Macht und Widerstand an.</warum3>
    <datum>2025-01-18</datum>
  </laraEingaben>

</formulareingaben>
